name: PilzServerJoin
author: ethanpilz
version: 1.0
description: Join the server with a firework.
main: com.ethanpilz.pilzserverjoin.Main
commands:
permissions:
    psj.firework:
        description: Player can join with a firework explosion.
        default: op